[workspace]
members = ["algo", "node-binding", "python-binding"]
resolver = "2"

[workspace.dependencies]
algo = { path = "algo" }
node-binding = { path = "node-binding" }
napi = { version = "2", no-default-features = true, features = ["full"] }
napi-derive = "2"


[profile.release]
lto = true
